server:
  port: 8084

spring:
  application:
    name: MicroService04

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/

#feign自带断路器，但是默认是没有打开的
feign:
  hystrix:
    enabled: true               #打开断路器
    polling-interval-ms: 2000   #刷新间隔

#zipkin服务地址
zipkin:
  base-url: http://localhost:9411
sleuth:
  sampler:
    probability: 1
