server:
  port: 8091
  registrycentery: 8761

spring:
  application:
    name: MicroService01

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:${server.registrycentery}/eureka/