spring:
  application:
    name: springcloud-config-client
  rabbitmq:
    host: 192.168.223.128
    port: 5672
    username: testmq
    password: testmq
    virtual-host: testhost
    connection-timeout: 10000s
  cloud:
    config:
      fail-fast: true
    bus:
      trace:
        enabled: true
      enabled: true

server:
  port: 9000
#management:
#  endpoints:
#    web:
#      exposure:
#        include: bus-refresh