server:
  port: 9111
spring:
  application:
    name: springcloud-bus-client
  rabbitmq:
    host: 192.168.223.128
    port: 5672
    username: testmq
    password: testmq


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true