server:
  port: 8889
spring:
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: gateway1
        uri: lb://MICROSERVICE01
        predicates:
        - Path=/service01/**
      - id: gateway2
        uri: lb://MICROSERVICE04
        predicates:
        - Path=/service04/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

# 配置Gateway日志等级，输出转发细节信息
logging:
  level:
    org.springframework.cloud.gateway: debug